# General
title: 5loaves2fish
subtitle: When you want more
description: When you want more

# landing type: index | single | page
landing: index
post-per-page: 2
archive: /archive
favicon: images/logo/logo-64x64.png
header:
  logo-img: images/logo/logo.png
  title-img: images/logo/5loaves2fish.png
  subtitle: When you want more

footer-script-note: "Crafted with <i class='fa fa-heart'></i> by <a href='http://5p2p.it'>5pani2pesci</a><br>Don't reproduce without permission."

facebook.app_id:
facebook.image:
google_analytics:

permalink: :title/
defaults:
  -
    scope:
      path: ""
    values:
      layout: "post"
